sudo: required
services:
  - docker

language: node_js

node_js:
  - "5"

git:
    submodules: false

env:
  global:
    - secure: "UnkjMMD5WA19zORlk1LECpO1GZfWvuM0WcVmougiuwlQhTPv697UMA1NEmTXNzMgF5DTEHNaBiIr9Q75woOzXnjJsTizsyUpwAQHP//s6ZTfuof3EUAQg3rX9tGj/KFHG3VuvDOlCnF6R1hc86jLTRL61DiWP/4+Q9Wn8JXeicPS2eI8ga+fVyTvgLtYZ//e+egyYK32dZyqvT0mlfFEpLBnMVmYzzi9SSHBu2otLLTvEray90V2afNamiqvb4Wwc9hGJF4fLZfMF8vuPqFztnA2imOdCtd1D3PZ6tNp3cXalqggn6aqkXwDoCZzmO3CHfLqIEqZuCeas0bwccApu5ZL14b/b618jwU9hoXhFHr+eZZxjoYqD0wRyJFH2fxbOWPzXJ05fpwY2s5Avflh7g1qhDmPsqc/O9SyplKqSvCeXdf+im/fesbZuzU1dDqX8ZXQFY4EK4ye+fORWzda/0Ltc0HMBVB44kz7wXbYlYT+10IqUZH7xidRVTAWRjpvUD1UzrJFr6N/WA2CQXUBr/VHbi23kVPoysZaZxZ2f9frfp0NNfUflMQhiKYiFuPf7D7j4DVLUX0QlUpmhTTGUsdodNpgTbvTszf7+vRHgLa4FbESn/ISbtOaFyIvqYTssezo8KAUrK50ABWKH0kt3VFydRQ61Qab5slVDl+NOBo="
    - secure: "F2TFYlVRGMb7u95e2wO8s1sG2ChZm/R3a2rxymXTcAif6m9ocpI6M7pWhgfLzR+ZHb9AOgCpbn0NcDHHSuBgYQjmwFV9BLcQ18/pKNIyP+Ei6kqJYMv5f7XAIm0/7DlpH28iHuyn5Fe/O027ItPg9fCDkqL2GjMn4dvmEYUAUmGkLmAWKZKz5lLNryLTDsB4ZaLWD+kUpVyYBixIk6cu02VMatc5v26tiRfVQsFvtpsETKGJPtoN+S1VEcB4/OBdodBXKtwAIOLw1x0DcIpTqD/UcTGyrS/P0H+47YuMnZ5d1l+KynCJiOy7OS12/5ViRbt9RAP2H2bit1s/FGZ2dvJAIXEgm9LRO3ewZaJWIQ90H0UywXU2NT42w6t+Brm15+3IxOJzJ1kFxSiule547NtCiookfY8Dypo3RPE33VI+z8W7ZjrgtU08pvzpZmrgHn3vsl8OCoDm4BRs/HUfWkxQAbr3jNVe8uSxsgDLDnAYN3/+luUnZkD7RAsHAiqi4EBFKlvaLYhsN+nD+V/cw5+DqEUyyF+7e3haK/AYzVP5z0r/5C5jqEp1dGGehJZJ1apyclFpMtDGmwt04GeSPldFTHgP2HSyNy2V1/pQMn+TcIHdajAticaXYWF3wSjt3TWxTD6bPxyiYNUTO/SQ780ddbt2hYKT271tNyPFyEQ="
    - secure: "eWiQ3SMI91oYuoHQpCeImDa+X29wbJJCk8LrRdhuKXNanW9eF8zfwBCmycxjSNFl4OcWzEs8EUBym1tj+hzQ41DEFV57svShB6Sw+R5zDwUwd1JigNvbtEZXLY6kURrKEqwMT3zyPi5ndGf6gl12hDByoa0HNBgYeDNs/MepogOmRVpUIlMBMZeq8IxQZOaG3DKP05zPHhSaM/jTt3EGkThUAElXvzpjFCr6z8JzKepxXKK2sctodrRQ8OwR4CPghUkDm9BvNixP06eM8tLsAThVlQg3Dt/fwtCteHhyN+axfBNJr36Sd6xg87g2DTK79L7KXRfKbMrH38gG5W8aCr4NOuer4U+2wHQ8KBJg/HyagdiS1x+Pih01TB9H8scepSx/TLqqtlu/VgFjC5lDclYZiKEkYfWIhDOPoVUq2N/8wCiuPHEDumS5xRcqlkK0+o+0J7Ell/g6GCB28wbJV2kme/AbwGFrlrLdE9SzszaAgFRNbHG6t1o/WuqPfRcyKbyM+L6NrCbGbmxNPwPgKyGYKUfaqdGMLABsc/EXvgKTkt/jUptyjNLPMw5JPYcJxw2frmok8O+IsL3qVcKhqW/6XUmR5LdoaLilNf7DpxkyTqwzC9TFfmc86v2TBuSz4CabkUYI5sIddbLJ1By7BpQrmjxijt/u1ksPYxYF0FY="


before_install:

    - git ..
    - git clone https://github.com/DinisCruz/BSIMM-Graphs-QA.git
    - cd BSIMM-Graphs-QA
    - git remote add upstream https://DinisCruz-Dev:$git_pwd@github.com/DinisCruz-Dev/BSIMM-Graphs-QA.git

    - git config --global user.email "bot@travis.com"
    - git config --global user.name "Travis Bot"

    - git log -n5 --pretty=oneline > git.log.txt
    - git add .
    - git commit -m 'added git.log.txt in travis CI'
    - git push -f upstream master

    - pwd
    - cd ..
    - ls
    - cd BSIMM-Graphs
    - ls -la


    #- echo 'building docker image'
    #- docker images
    #- docker build --no-cache -t diniscruz/bsimm-graphs ./deploy/docker-images/bsimm-graphs/
    #- docker images
    #- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
    #- docker push diniscruz/bsimm-graphs

    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive

before_script:

  - npm install -g bower
  - bower install



after_success:

  - git config --global user.email "bot@travis.com"
  - git config --global user.name "Travis Bot"

  - git add .

  - git commit -m 'custom update to .gitmodules (for snap-ci)'
  - echo "pushing changes to DinisCruz-Dev fork, which will trigger a docker cloud build"
  - git push -f https://DinisCruz-Dev:$git_pwd@github.com/DinisCruz-Dev/BSIMM-Graphs.git master
