language: node_js

node_js:
  - "5"

git:
    submodules: false

before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive

before_script:

  - npm install -g bower
  - bower install

after_success:
  - echo "pushing changes to DinisCruz-Dev fork, which will trigger a docker cloud build"
  - git push -f https://DinisCruz-Dev:$git_pwd@github.com/DinisCruz-Dev/BSIMM-Graphs.git master
