language: node_js

node_js:
  - "5"

git:
    submodules: false

before_install:

    - echo 'building docker image'
    - docker images
    - docker build --no-cache -t diniscruz/bsimm-graphs /deploy/docker-images/bsimm-graphs/
    - docker images

    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive

before_script:

  - npm install -g bower
  - bower install



after_success:


  - git add .
  - git commit -m 'custom update to .gitmodules (for snap-ci)'
  - echo "pushing changes to DinisCruz-Dev fork, which will trigger a docker cloud build"
  - git push -f https://DinisCruz-Dev:$git_pwd@github.com/DinisCruz-Dev/BSIMM-Graphs.git master
